HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}

SOURCES = {
    "vnexpress": {
        "type": "html",
        "url": "https://vnexpress.net/khoa-hoc-cong-nghe",
        "base_url": "https://vnexpress.net",
        "article_selector": "article.item-news",
        "a_selector": "h3.title-news a, h4.title-news a",
        "date_selector": "meta[name='pubdate']",
        "content_selector": "article.fck_detail p",
        "rss_url": "https://vnexpress.net/rss/khoa-hoc-cong-nghe.rss",
        "pagination": {
            "pattern": "https://vnexpress.net/khoa-hoc-cong-nghe-p{page}",
            "start": 2,
            "max_pages": 3,
        },
    },
    "thanhnien": {
        "type": "html",
        "url": "https://thanhnien.vn/cong-nghe.htm",
        "base_url": "https://thanhnien.vn",
        "article_selector": "div.box-category-item",
        "a_selector": "a.box-category-link-with-avatar",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div.detail-content--mainContent p, div[class*='mainContent'] p, div.detail-content p",
        "rss_url": "https://thanhnien.vn/rss/cong-nghe.rss",
        "pagination": {
            "pattern": "https://thanhnien.vn/cong-nghe/trang-{page}.htm",
            "start": 2,
            "max_pages": 3,
        },
    },
    "tuoitre": {
        "type": "rss",
        "url": "https://tuoitre.vn/cong-nghe.htm",
        "base_url": "https://tuoitre.vn",
        "article_selector": "div.box-category-item",
        "a_selector": "a.box-category-link-title",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div#main-detail p",
        "rss_url": "https://tuoitre.vn/rss/cong-nghe.rss",
    },
    "zingnews": {
        "type": "rss",
        "url": "https://znews.vn/cong-nghe.html",
        "base_url": "https://znews.vn",
        "article_selector": "article.article-item",
        "a_selector": "p.article-title a",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div.the-article-body p, p.article-sapo",
        "rss_url": "https://zingnews.vn/rss/cong-nghe.rss",
    },
    "cafebiz": {
        "type": "rss",
        "url": "https://cafebiz.vn/cong-nghe.chn",
        "base_url": "https://cafebiz.vn",
        "article_selector": "div.list-news-item",
        "a_selector": "h3 a",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div.detail-content p, div[class*='detail'] p, article p",
        "rss_url": "https://cafebiz.vn/rss/cong-nghe.rss",
    },
    "vietnamnet": {
        "type": "rss",
        "url": "https://vietnamnet.vn/cong-nghe",
        "base_url": "https://vietnamnet.vn",
        "article_selector": "div.horizontalPost",
        "a_selector": "h3.horizontalPost__main-title a",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div.maincontent p",
        "rss_url": "https://vietnamnet.vn/rss/cong-nghe.rss",
    },
    "trainghiemso": {
        "type": "rss",
        "url": "https://trainghiemso.vn",
        "base_url": "https://trainghiemso.vn",
        "article_selector": "",
        "a_selector": "",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "div.entry-content p, div.post-content p, article.post p",
        "rss_url": "https://trainghiemso.vn/feed/",
    },
    "dantri": {
        "type": "rss",
        "url": "https://dantri.com.vn/cong-nghe.htm",
        "base_url": "https://dantri.com.vn",
        "article_selector": "article.article-item",
        "a_selector": "h3.article-title a",
        "date_selector": "meta[property='article:published_time']",
        "content_selector": "",
        "rss_url": "https://dantri.com.vn/rss/cong-nghe.rss",
    },
}